backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "Index Page"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - {
              label: "Path",
              name: "path",
              widget: "hidden",
              default: "/"  
            }
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
          - label: Workshops
            name: workshops
            widget: list
            fields:
              - { label: Titel, name: title, widget: string }
              - { label: Start, name: start, widget: datetime }
              - { label: Ende, name: end, widget: datetime }
              - { label: Beschreibung, name: description, widget: text }
              - { label: Ort, name: place, widget: string }
              - { label: Verantwortlicher, name: person, widget: string }
              - { label: Plätze, name: count, widget: number }
              - label: Status
                name: state
                widget: select
                options:
                  - { label: Aktiv, value: av }
                  - { label: Voll, value: fu }
                  - { label: Keine Anmeldung nötig, value: na }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/info/index.md"
        label: "Weitere Informationen"
        name: "info"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - {
              label: "Path",
              name: "path",
              widget: "hidden",
              default: "info"  
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/about/index.md"
        label: "Über uns"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - {
              label: "Path",
              name: "path",
              widget: "hidden",
              default: "about"  
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/impressum/index.md"
        label: "Impressum"
        name: "impressum"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - {
              label: "Path",
              name: "path",
              widget: "hidden",
              default: "impressum"  
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
